# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b1d912efbbf88db9ee73e8ff5aaa9e785da6139892b8f80caf94f840d45804ac9953fec8005ad21315961d5aeeba56e5b6030d566841e7d94fc3b3c873a6a1

test:
  secret_key_base: c06a4ba562674b6e29ec00587b14c60da07d1fa1058879852854892d1ee9e49d7b21b89c51f0b13b1740126d4873599f60394f0ec7de69df0ba1130315035b6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
